<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Api2cart_BridgeConnector::css/styles.css')?>">
<script src="<?php echo $block->getViewFileUrl('Api2cart_BridgeConnector::js/jquery/script.js')?>" ></script>

<div class="section-config active">
  <input id="bridge_general-state" name="config_state[bridge_general]" type="hidden" value="1">
  <div id="bridge_general">
    <script>
      var SELF_PATH = '<?php  /* @var $block \Api2cart\BridgeConnector\Block\Adminhtml\BridgeConnector*/ echo $block->getRouteUrl('bridgeconnector/bridgeconnector'); ?>';
      var bridgeInstalledMsg = '<b>Congratulations! The plugin is installed!</b><br><br><b>Please note.</b> Store data interaction works if you are integrated with the service only.It enables to retrieve, synchronize, and manipulate various information on products, categories, customers, and orders from the store.';
      var bridgeNotInstalledMsg = '<p id="connector-installed-txt" style="display: block;">The connection bridge will be installed automatically. Just click the button below.</p>';
      var buttonInstallMsg = 'Install Connector';
      var buttonUninstallMsg = 'Uninstall Connector';
    </script>
    <div style="position: relative;">
      <div class="message"></div>
    </div>
    <div class="container">
      <div class="bridge">
        <div class="container">
          <div class="text-center" id="content-block"></div><br/>
          <div class="text-center">
            <div class="progress progress-dark progress-small progress-striped active">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>

            <div class="store-key">
              <span class="store-key-title">Your store key:</span>
              <input class="store-key-content" id="storeKey" title="Your store key" type="text" name="comment" size="36" value="<?php echo $block->getStoreKey(); ?>" readonly/>
              <button id="updateBridgeStoreKey" class="btn-update-store-key">Update Store Key</button>
            </div>
            <button id="btn-setup" class="<?php echo $block->getButtonClass();?> btn-setup">
                <?php echo $block->getButtonText();?>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
